### PR TITLE
fix: null value reference when copy_action is specified without lifecycle options

### PR DESCRIPTION
**Pull request by carlosaml**
## what

`Attempt to get attribute from null value` error when a `copy_action` is specified in a backup rule without any lifecycle options

### steps to reproduce

Based on the complete example:

```

module "backup" {
  source = "../.."

  backup_resources = [module.efs.arn]
  not_resources    = var.not_resources

  rules = [
    {
      name              = "${module.this.name}-daily"
      schedule          = var.schedule
      start_window      = var.start_window
      completion_window = var.completion_window
      lifecycle = {
        cold_storage_after = var.cold_storage_after
        delete_after       = var.delete_after
      }
      copy_action = {
        destination_vault_arn = "arn:aws:backup:us-east-2:123456789000:backup-vault:my-vault"
      }
    }
  ]

  backup_vault_lock_configuration = {
    max_retention_days = 365
    min_retention_days = 30
  }

  context = module.this.context
}
```

## why

The following error should **not** happen:

```
╷
│ Error: Attempt to get attribute from null value
│
│   on ../../main.tf line 79, in resource "aws_backup_plan" "default":
│   79:               cold_storage_after = rule.value.copy_action.lifecycle.cold_storage_after
│     ├────────────────
│     │ rule.value.copy_action.lifecycle is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on ../../main.tf line 80, in resource "aws_backup_plan" "default":
│   80:               delete_after       = rule.value.copy_action.lifecycle.delete_after
│     ├────────────────
│     │ rule.value.copy_action.lifecycle is null
│
│ This value is null, so it does not have any attributes.
╵
```

### CODE REVIEW

**Comment by gberenice** [comment]
@carlosaml ah, could you also add fixes to satisfy the check?
```
Running output-descriptions in /__w/terraform-aws-backup/terraform-aws-backup/examples/complete

Test: check if terraform outputs have descriptions
File: output-descriptions.bats
---------------------------------
private_subnet_cidrs is missing a description
public_subnet_cidrs is missing a description
vpc_cidr is missing a description
---------------------------------
```

**Comment by carlosaml** [comment]
@gberenice done

**Comment by gberenice** [comment]
@carlosaml thank you for fixes! Unfortunately, there is the similar issue for inputs:
```
Running input-descriptions in /__w/terraform-aws-backup/terraform-aws-backup

Test: check if terraform inputs have descriptions
File: input-descriptions.bats
---------------------------------
advanced_backup_setting is missing a description
---------------------------------
```

**Comment by carlosaml** [comment]
@gberenice there we go

**Review by gberenice — APPROVED** [review]

**Pull request merged**
